// Production schema — always PostgreSQL.
// Local dev uses schema-sqlite.ts directly (via server/index.ts dynamic import).
// Tests import schema-sqlite.ts directly.

export {
  users,
  years,
  teams,
  kaks,
  champs,
  boots,
  tieBreakAdjustments,
  fishWeights,
  chugTimes,
  golfScores,
  kaksRelations,
  yearsRelations,
  teamsRelations,
  champsRelations,
  bootsRelations,
  tieBreakAdjustmentsRelations,
  fishWeightsRelations,
  chugTimesRelations,
  golfScoresRelations,
  registerUserSchema,
  insertYearSchema,
  insertTeamSchema,
  insertKakSchema,
  insertChampSchema,
  insertBootSchema,
  insertTieBreakAdjustmentSchema,
  insertFishWeightSchema,
  insertChugTimeSchema,
  insertGolfScoreSchema,
} from "./schema-postgres.js";

export type {
  RegisterUser,
  User,
  InsertYear,
  Year,
  InsertTeam,
  Team,
  InsertKak,
  Kak,
  InsertChamp,
  Champ,
  InsertBoot,
  Boot,
  InsertTieBreakAdjustment,
  TieBreakAdjustment,
  InsertFishWeight,
  FishWeight,
  InsertChugTime,
  ChugTime,
  InsertGolfScore,
  GolfScore,
} from "./schema-postgres.js";
